
#### general settings

name: train_MIMO-VRN_gof5_lambda64
use_tb_logger: true
model: MIMO-VRN
distortion: sr
scale: 4
gpu_ids: [0, 1]
gop: 5

#### datasets

datasets:
  train:
    name: Vimeo90K
    mode: Vimeo90K
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: ~/datasets/vimeo90k/vimeo90k_train_GT7.lmdb
    dataroot_LQ: ~/vimeo90k/vimeo90k_train_LR7frames.lmdb
    cache_keys: Vimeo90K_train_keys.pkl

    N_frames: 7
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 144
    LQ_size: 36
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: Vid4
    mode: video_test
    dataroot_GT: ~/Vid4/HR
    dataroot_LQ: ~/Vid4/LR_bicubic/X4

    N_frames: 1
    padding: 'new_info'
    pred_interval: -1


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [8, 8]
  scale: 4
  init: xavier
  block_num_rbm: 8


#### path

path:
  pretrain_model_G:
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:

  lr_G: !!float 1e-4
  beta1: 0.9
  beta2: 0.5
  niter: 250000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [30000, 60000, 90000, 150000, 180000, 210000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  manual_seed: 10

  val_freq: !!float 5e3

  lambda_fit_forw: 64.
  lambda_rec_back: 1
  lambda_center: 0

  weight_decay_G: !!float 1e-12
  gradient_clipping: 10


#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
